# Generated by Django 5.2.10 on 2026-01-12 10:05

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractors', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('ACCOUNT_MANAGER', 'Account Manager'), ('BUDGET_MANAGER', 'Budget Manager'), ('CONSTRUCTION_MANAGER', 'Construction Manager'), ('SUBCEO', 'Sub CEO'), ('SUB_ACCOUNT_MANAGER', 'Sub Account Manager'), ('SUB_BUDGET_MANAGER', 'Sub Budget Manager'), ('SUB_CONSTRUCTION_MANAGER', 'Sub Construction Manager')], max_length=40)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models.default_invitation_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='accounts_in_token_be8e6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('ACCOUNT_MANAGER', 'Account Manager'), ('BUDGET_MANAGER', 'Budget Manager'), ('CONSTRUCTION_MANAGER', 'Construction Manager'), ('SUBCEO', 'Sub CEO'), ('SUB_ACCOUNT_MANAGER', 'Sub Account Manager'), ('SUB_BUDGET_MANAGER', 'Sub Budget Manager'), ('SUB_CONSTRUCTION_MANAGER', 'Sub Construction Manager')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
