# Generated by Django 5.2.10 on 2026-01-12 11:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='budgets/excel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='construction.order')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='budgets.budget')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budgets.budgetheader')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('measure_unit', models.CharField(blank=True, max_length=50)),
                ('price_for_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budgetheader')),
            ],
            options={
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decline_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decline_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='budgets.budget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItemAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_amounts', to='budgets.budgetitem')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_amounts', to='budgets.budgetperiod')),
            ],
        ),
        migrations.AddConstraint(
            model_name='budgetperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('budget',), name='unique_open_period_per_budget'),
        ),
        migrations.AddConstraint(
            model_name='budgetitemamount',
            constraint=models.UniqueConstraint(fields=('period', 'budget_item'), name='unique_amount_per_item_period'),
        ),
    ]
