# Generated by Django 5.2.10 on 2026-01-12 10:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_organizationmembership_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructions', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='construction.construction')),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractForWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100)),
                ('contractor_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('contract_signed', models.DateTimeField(blank=True, null=True)),
                ('day_after_due', models.IntegerField(default=0)),
                ('end_contract', models.DateField(blank=True, null=True)),
                ('is_social_house', models.BooleanField(default=False)),
                ('start_contract', models.DateField(blank=True, null=True)),
                ('tax_reverse_charge', models.BooleanField(default=False)),
                ('warranty_period', models.IntegerField(default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='construction.order')),
            ],
            options={
                'ordering': ['contract_number'],
            },
        ),
        migrations.CreateModel(
            name='Residual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('percentage', models.IntegerField()),
                ('contract_for_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residuals', to='construction.contractforwork')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
    ]
